services:
  mysql:
    container_name: 'mysql-finance'
    image: 'mysql:8.0.35'
    environment:
      - 'MYSQL_ROOT_PASSWORD=root123'
      - 'MYSQL_DATABASE=financedb'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=123'
    ports:
      - '3306:3306'
